const defaultPreferences = {
  app: {
    accessMode: 'frontend',
    checkUpdatesInterval: 1,
    defaultHomePath: '/analytics',
    dynamicTitle: true,
    enableCheckUpdates: true,
    enablePreferences: true,
    enableRefreshToken: false,
    isMobile: false,
    locale: 'zh-CN',
    name: 'Plus Admin',
    watermark: false,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: false,
  },
  copyright: {
    companyName: 'ZehuiChan_ Design.',
    companySiteLink: 'https://zehuichan.github.io/vite-element-plus-admin/',
    date: '2024',
    enable: true,
    icp: 'ICP 备案号',
    icpLink: 'ICP 网站链接',
  },
  footer: {
    enable: true,
    fixed: false,
  },
  header: {
    enable: true,
    hidden: false,
    mode: 'fixed',
    height: 50,
  },
  logo: {
    enable: false,
    source: ''
  },
  navigation: {
    accordion: true,
    colorBg: '#1c1e23',
    colorHoverBg: 'hsl(0 0% 0% / 98%)',
    colorText: '#ffffffb3',
    colorHoverText: 'hsl(0 0% 98%)',
    colorActiveText: 'hsl(212 100% 45%)',
  },
  shortcutKeys: {
    enable: true,
    globalLogout: true,
    globalPreferences: true,
    globalSearch: true,
    globalInformation: true,
  },
  sidebar: {
    collapsed: false,
    enable: true,
    hidden: false,
    width: 224,
    collapseWidth: 64,
  },
  tabbar: {
    dragable: true,
    enable: true,
    height: 40,
    keepAlive: true,
    persist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    showRefresh: true,
    styleType: 'chrome',
  },
  theme: {
    builtinType: 'default',
    colorDestructive: 'hsl(348 100% 61%)',
    colorPrimary: 'hsl(212 100% 45%)',
    colorSuccess: 'hsl(144 57% 58%)',
    colorWarning: 'hsl(42 84% 61%)',
    mode: 'dark',
    radius: '0.5',
    semiDarkHeader: false,
    semiDarkSidebar: true,
  },
  transition: {
    enable: true,
    loading: true,
    name: 'fade-slide',
    progress: true,
  },
  widget: {
    fullscreen: true,
    globalSearch: true,
    languageToggle: true,
    lockScreen: true,
    notification: true,
    refresh: true,
    sidebarToggle: true,
    themeToggle: true,
  },
}

export { defaultPreferences }
